apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.25.1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: ALLOW_SIGNUP
              value: "false"
            - name: BASE_URL
              value: "https://mealie.scottccourt.com"
            - name: OIDC_AUTH_ENABLED
              value: "True"
            - name: OIDC_SIGNUP_ENABLED
              value: "True"
            - name: OIDC_AUTO_REDIRECT
              value: "False"
            - name: OIDC_PROVIDER_NAME
              value: "Authentik"
            - name: OIDC_CONFIGURATION_URL
              value: "https://auth.scottccourt.com/application/o/mealie/.well-known/openid-configuration"
            - name: OIDC_CLIENT_ID
              value: "ZDNWxfq7rqmeOQkWTcazWHgUt6xuZlWQHIx269Qk"
            - name: OIDC_CLIENT_SECRET
              value: "p0Ve7CmKujkpm7E6nS2d0V0fP4yeaqzJ7X7lZX4XXX6wwJkfQT11Dj4szPBlKgvyeS3XcEBdyYrObMbz6qCaCY2W1IWdrye2cIETxx4dFYRauxxaOxrxPoCi3fCAwM4f"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie-data
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
spec:
  selector:
    app: mealie
  ports:
    - port: 9000
      targetPort: 9000