apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amp-tls
  namespace: default
spec:
  secretName: amp-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - amp.scottccourt.com