apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/longhorn/longhorn
    targetRevision: v1.7.2
    path: chart
    helm:
      values: |
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true